export const TRIPS_ACTION_TYPES = {
    FETCH_TRIPS_REQUEST: "FETCH_TRIPS_REQUEST",
    FETCH_TRIPS_SUCCESS: "FETCH_TRIPS_SUCCESS",
    FETCH_TRIPS_ERROR: "FETCH_TRIPS_ERROR",
    FETCH_TRIP_REQUEST: "FETCH_TRIP_REQUEST",
    FETCH_TRIP_SUCCESS: "FETCH_TRIP_SUCCESS",
    FETCH_TRIP_ERROR: "FETCH_TRIP_ERROR",
    BOOK_TRIP_REQUEST: "BOOK_TRIP_REQUEST",
    BOOK_TRIP_SUCCESS: "BOOK_TRIP_SUCCESS",
    BOOK_TRIP_ERROR: "BOOK_TRIP_ERROR"
};

export const LOADING_STATES = {
    IDLE: "IDLE",
    LOADING: "LOADING",
    LOADED: "LOADED",
    ERROR: "ERROR"
};

export const STATUS = {
    UNKNOWN: "UNKNOWN",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR"
};
